apiVersion: v1
kind: Service
metadata:
  name: {{ include "spartan-project.fullname" . }}
  labels:
    {{- include "spartan-project.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetport }}
      nodePort: {{ .Values.service.nodeport }}
    - protocol: TCP
      port: {{ .Values.servicessl.port }}
      targetPort: {{ .Values.servicessl.targetport }}
      nodePort: {{ .Values.servicessl.nodeport }}
  selector:
    {{- include "spartan-project.selectorLabels" . | nindent 4 }}
