apiVersion: v1
kind: ConfigMap
metadata:
  name: delta-configurations
data:
  postgresconnectionstring: 'Host=delta-db-postgresql.postgres-db.svc.cluster.local;Database=postgres;Username=postgres;Password=hA3kli1d2Z;Pooling=false;Timeout=300;CommandTimeout=300'
  tz: 'America/Chihuahua'
  nls_timestamp_format: 'YYYY-MM-DD HH:MI'
  lang: 'es_ES.utf8'
  aspnetcore_environment: "Production"
  aws_access_key_id: 'AKIA32C73V5WYQMZ3RQI'
  aws_secret_access_key: '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'
  aws_default_region: 'us-west-1'