apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-delta-db-postgresql-0
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi